import { test, expect } from '@playwright/test';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createApp } from '../backend/src/app.js';
import { hashPassword } from '../backend/src/auth.js';
import { startTestMongo, testDatabaseName } from '../backend/tests/mongo.js';

let app, directory, mongo;
const base = 'http://127.0.0.1:3107';
const password = 'browser-test-password-123';
test.beforeAll(async () => {
  directory = mkdtempSync(join(tmpdir(), 'rapid-nova-browser-'));
  mongo = await startTestMongo();
  app = await createApp({ mongoUri: mongo.getUri(), databaseName: testDatabaseName(), distDir: resolve('dist'), admin: { email: 'team@example.test', passwordHash: await hashPassword(password) }, publicOrigin: base });
  await new Promise(done => app.server.listen(3107, '127.0.0.1', done));
});
test.afterAll(async () => { await app?.close(); await mongo?.stop(); if (directory) rmSync(directory, { recursive: true, force: true }); });

test('publish a job, apply with a CV, submit enquiries, and review in admin', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}/admin`);
  await page.getByLabel('Email address').fill('team@example.test');
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByRole('button', { name: /Vacancies/ }).click();
  await page.getByRole('button', { name: 'Create Vacancy' }).click();
  await page.getByLabel('Job title').fill('Travel Registered Nurse');
  await page.getByLabel('Location', { exact: false }).fill('Test City');
  await page.getByLabel('Description and requirements').fill('A test vacancy for a qualified registered nurse.');
  await page.getByRole('button', { name: 'Save Vacancy' }).click();
  await expect(page.getByRole('heading', { name: 'Travel Registered Nurse' })).toBeVisible();
  await page.goto(base);
  await expect(page.getByRole('heading', { name: 'Travel Registered Nurse' })).toBeVisible();
  await page.getByRole('link', { name: 'Apply for this role' }).click();
  const application = page.locator('#apply');
  await expect(application.getByText('Applying for Travel Registered Nurse', { exact: false })).toBeVisible();
  await application.getByLabel('Full name').fill('Browser Candidate');
  await application.getByLabel('Email address').fill('candidate@example.test');
  await application.getByLabel('Preferred location').fill('Test City');
  await application.getByLabel('Your CV').setInputFiles({ name: 'candidate.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF') });
  await application.getByRole('checkbox').check();
  await application.getByRole('button', { name: 'Submit Application' }).click();
  await expect(application.getByText('Thank you. Your submission has been received.')).toBeVisible();
  const contact = page.locator('#contact');
  await contact.getByLabel('Your name').fill('Browser Facility');
  await contact.getByLabel('Email address').fill('facility@example.test');
  await contact.getByLabel('Facility or organisation').fill('Test Clinic');
  await contact.getByLabel('Role needed').fill('Allied Health');
  await contact.getByLabel('Facility location').fill('Test City');
  await contact.getByRole('checkbox').check();
  await contact.getByRole('button', { name: 'Submit Staffing Request' }).click();
  await expect(contact.getByText('Thank you. Your submission has been received.')).toBeVisible();
  await contact.getByRole('button', { name: 'General Enquiry' }).click();
  await contact.getByLabel('Your name').fill('Browser Contact');
  await contact.getByLabel('Email address').fill('contact@example.test');
  await contact.getByLabel('Your message').fill('Please contact me about your services.');
  await contact.getByRole('checkbox').check();
  await contact.getByRole('button', { name: 'Send Message' }).click();
  await expect(contact.getByText('Thank you. Your submission has been received.')).toBeVisible();
  await page.goto(`${base}/admin`);
  await expect(page.getByRole('heading', { name: 'Browser Candidate' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Browser Facility' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Browser Contact' })).toBeVisible();
  const candidate = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Browser Candidate' }) });
  await candidate.getByLabel('Status').selectOption('contacted');
  await candidate.getByLabel('Internal notes').fill('Ready for a call.');
  await candidate.getByRole('button', { name: 'Save Changes' }).click();
  await expect(candidate.getByText('Changes saved.')).toBeVisible();
  const downloadPromise = page.waitForEvent('download'); await candidate.getByRole('link', { name: 'Download CV (PDF)' }).click();
  expect((await downloadPromise).suggestedFilename()).toMatch(/^cv-.*\.pdf$/);
  await page.reload(); await expect(candidate.getByLabel('Status')).toHaveValue('contacted'); await expect(candidate.getByLabel('Internal notes')).toHaveValue('Ready for a call.');
  await page.getByRole('button', { name: 'Sign Out' }).click();
  await expect(page.getByRole('heading', { name: 'Team Sign In' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('mobile layout fits the screen and navigation reaches application form', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto(base);
  await page.getByRole('button', { name: 'Toggle menu' }).click();
  await page.getByRole('link', { name: 'Apply Now', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Toggle menu' })).toHaveAttribute('aria-expanded', 'false');
  await expect(page.getByRole('heading', { name: 'Apply with Rapid Nova' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile-application.png' });
});
