import { useState } from 'react';
import hospitalNurses from './assets/hospital-nurses.jpg';
import patientCare from './assets/patient-care.jpg';
import internationalTeam from './assets/international-team.jpg';
import { uniquePhotos } from './UniquePhotos';



const paths = [
  { title: 'Travel nursing', tag: 'A CHANGE OF SCENE', image: hospitalNurses, alt: 'Nurses walking together in a bright hospital corridor', text: 'Bring your experience somewhere new. Explore assignments matched to your specialty, preferred location, and availability.', query: 'Travel' },
  { title: 'Local & per diem', tag: 'CLOSER TO WHAT MATTERS', image: patientCare, alt: 'A nurse talking with an older patient in a consultation room', text: 'Keep your community close. Discuss local roles and shift-based opportunities that suit your working preferences.', query: 'Per diem' },
  { title: 'International nursing', tag: 'A WORLD OF POSSIBILITY', image: internationalTeam, alt: 'Healthcare professionals talking beside hospital windows', text: 'Take your clinical experience beyond borders. Understand the requirements and ask about available destinations.', href: '/international-nursing' },
];
export function PhotoPaths({ showImages = true }) {
  return <section className="rn-photo-paths"><div className="wrap"><div className="rn-heading-row"><div><span className="kicker">MAKE ROOM FOR YOUR AMBITION</span><h2>A career that moves<br /><em>the way you do.</em></h2></div><p>New places, familiar communities, or a fresh start. Explore the possibilities and decide what your next chapter could look like.</p></div><div className="rn-photo-path-grid">{paths.map(item => <a className="rn-photo-path" key={item.title} href={item.href || '/careers#jobs'} data-job={item.query}>{showImages && <div className="rn-path-image"><img src={item.image} alt={item.alt} loading="lazy" width="1536" height="1024" /><span>{item.tag}</span></div>}<div className="rn-path-copy"><h3>{item.title}</h3><p>{item.text}</p><span className="rn-path-link">Explore this path <span aria-hidden="true">↗</span></span></div></a>)}</div></div></section>;
}

const placementOptions = [
  { title: 'Travel assignments', heading: 'New settings. Fresh perspective.', image: hospitalNurses, text: 'A change of location can bring new clinical experiences and a different pace of life. Discuss assignment length, shift patterns, and start dates for each available role.', checklist: ['Confirm the assignment dates and schedule', 'Discuss travel and housing arrangements', 'Review registration requirements for the location'], query: 'Travel' },
  { title: 'Local & per diem', heading: 'Your skills. Your community.', image: patientCare, text: 'Local work can let you stay close to home while exploring a different care setting. Ask about available shifts, minimum commitments, and how scheduling works.', checklist: ['Clarify shift availability and commitments', 'Check the commute and facility setting', 'Discuss orientation and cancellation policies'], query: 'Per diem' },
  { title: 'Permanent roles', heading: 'Put down roots. Keep growing.', image: internationalTeam, text: 'For your next long-term move, consider the clinical team, development opportunities, and working culture. Review the employer’s offer and expectations before deciding.', checklist: ['Understand the employer’s benefits package', 'Discuss onboarding and development', 'Confirm employment terms and start date'], query: 'Permanent' },
];
export function PlacementExplorer() {
  const [active, setActive] = useState(0);
  const option = placementOptions[active];
  return <section className="rn-placement-explorer" id="placement-types"><div className="wrap"><div className="section-head"><span className="kicker">CHOOSE HOW YOU WANT TO WORK</span><h2>Your career. <em>Your direction.</em></h2><p>Compare working arrangements and the questions to ask before your next move.</p></div><div className="rn-placement-tabs" role="tablist" aria-label="Compare placement types">{placementOptions.map((item, index) => <button id={`placement-tab-${index}`} key={item.title} type="button" role="tab" aria-selected={active === index} aria-controls="placement-panel" tabIndex={active === index ? 0 : -1} onClick={() => setActive(index)} onKeyDown={event => { if (['ArrowRight', 'ArrowLeft', 'Home', 'End'].includes(event.key)) { event.preventDefault(); const next = event.key === 'Home' ? 0 : event.key === 'End' ? placementOptions.length - 1 : (active + (event.key === 'ArrowRight' ? 1 : -1) + placementOptions.length) % placementOptions.length; setActive(next); document.getElementById(`placement-tab-${next}`)?.focus(); } }}>{item.title}</button>)}</div><div className="rn-placement-panel" id="placement-panel" role="tabpanel" aria-labelledby={`placement-tab-${active}`} tabIndex={0}><img src={uniquePhotos.careerConversation} alt="A nurse discussing career plans with a recruitment professional" loading="lazy" width="1536" height="1024" /><div key={option.title} className="rn-placement-copy"><span className="kicker">{option.title}</span><h3>{option.heading}</h3><p>{option.text}</p><ul>{option.checklist.map(text => <li key={text}>{text}</li>)}</ul><a href="/careers#jobs" data-job={option.query} className="btn btn-capri">Search {option.title.toLowerCase()} →</a></div></div></div></section>;
}

export function Specialties() {
  return <section className="rn-specialties" id="specialties"><div className="wrap"><span className="kicker">BRING YOUR SPECIALTY INTO FOCUS</span><h2>Where does your <em>expertise belong?</em></h2><p>Search published roles by specialty. Availability depends on current facility needs.</p><div className="rn-specialty-links">{['Medical Surgical', 'Intensive Care', 'Emergency', 'Labor & Delivery', 'Operating Room', 'Pediatrics', 'Telemetry', 'Long-Term Care'].map(specialty => <a href="/careers#jobs" data-job={specialty} key={specialty}>{specialty}<span aria-hidden="true">↗</span></a>)}</div></div></section>;
}

export function PayAndSupport() {
  return <section className="rn-pay-support"><div className="wrap rn-support-grid"><div className="rn-support-portrait"><img src={uniquePhotos.therapySession} alt="A physical therapist supporting a patient during a balance exercise" loading="lazy" width="1536" height="1024" /><span>THE WORK YOU DO MATTERS.</span></div><div><span className="kicker">KNOW WHAT YOUR NEXT ROLE OFFERS</span><h2>More clarity.<br /><em>A better-informed move.</em></h2><p>Pay and support vary by employer and placement. Use the conversation to understand the full offer, beyond the headline rate.</p><div className="rn-offer-grid">{[['Pay & schedule', 'Confirm the rate, hours, overtime arrangements, and payment schedule.'], ['Benefits & wellbeing', 'Ask what insurance, leave, and other benefits apply to your employment type.'], ['Housing & travel', 'For a move, clarify accommodation, travel costs, and any available assistance.'], ['Credentials & onboarding', 'Discuss required documents, screening, orientation, and who handles each step.']].map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><a href="/contact" className="text-link">Discuss your career questions →</a></div></div></section>;
}

export function InternationalPreparation() {
  return <section className="rn-global-preparation"><div className="wrap"><div className="rn-global-photo"><img src={uniquePhotos.houstonCity} alt="Houston skyline seen from a landscaped city park" loading="lazy" width="1536" height="1024" /><div><span className="kicker">A NEW DESTINATION. A THOUGHTFUL START.</span><h2>Bring your passion.<br /><em>Prepare your next move.</em></h2></div></div><div className="rn-preparation-grid">{[['Your professional background', 'Keep a clear record of your qualifications, registration, recent clinical experience, and specialty skills.'], ['Your destination requirements', 'Confirm the registration, language, and work authorisation requirements relevant to the specific destination and vacancy.'], ['Your employer arrangements', 'Ask about sponsorship, relocation, offer terms, and any support for dependants before making travel plans.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>;
}

export function CareerGuides() {
  const guides = [
    ['resume-guide', uniquePhotos.resumePlanning, 'APPLICATION GUIDE', 'A resume that tells your clinical story', 'Make your experience easy to understand before you apply.', ['Include your qualifications and current professional registration.', 'List recent roles with dates, care settings, and core responsibilities.', 'Highlight specialties, relevant skills, and your preferred role or location.', 'Save a clear PDF under 3 MB for the Rapid Nova application.']],
    ['assignment-guide', uniquePhotos.offerReview, 'PLACEMENT CHECKLIST', 'Before you say yes to your next role', 'Turn a promising opportunity into an informed decision.', ['Confirm duties, location, schedule, assignment length, and start date.', 'Review pay, benefits, and any travel or accommodation arrangements.', 'Ask what documents and onboarding steps are required.', 'Understand offer terms and clarify outstanding questions with the team.']],
    ['international-guide', uniquePhotos.travelPlanning, 'INTERNATIONAL GUIDE', 'Planning a move beyond borders', 'Start with your background and confirm the details for your destination.', ['Keep an up-to-date resume and details of your qualifications and registration.', 'Ask which requirements apply to your preferred destination and vacancy.', 'Clarify sponsorship, relocation support, and responsibility for costs.', 'Confirm the offer and relevant approvals before arranging your move.']],
  ];
  return <section className="rn-career-guides" id="guides"><div className="wrap"><div className="rn-heading-row"><div><span className="kicker">YOUR CAREER TOOLKIT</span><h2>A little guidance.<br /><em>A clearer way forward.</em></h2></div><p>Practical checklists you can use for your next application, offer conversation, or international enquiry.</p></div><div className="rn-guide-grid">{guides.map(([id, image, category, title, text, checklist]) => <article id={id} key={id}><img src={image} alt={({ 'resume-guide': 'A healthcare professional preparing a resume at a desk', 'assignment-guide': 'A nurse reviewing an offer with a recruiter', 'international-guide': 'A nurse preparing a suitcase for travel' })[id]} loading="lazy" width="1536" height="1024" /><div><span className="kicker">{category}</span><h3>{title}</h3><p>{text}</p><details><summary>Read the checklist <span aria-hidden="true">+</span></summary><ul>{checklist.map(line => <li key={line}>{line}</li>)}</ul></details></div></article>)}</div></div></section>;
}
