import { uniquePhotos } from './UniquePhotos';

export default function DirectHireCareer({ compact = false }) {
  return <section className="rn-direct-hire" id="direct-hire"><div className="wrap">
    <div className={`rn-direct-hire-grid${compact ? ' rn-direct-hire-teaser' : ''}`}>{!compact && <div className="rn-direct-hire-photo"><img src={uniquePhotos.internationalArrival} alt="A nurse arriving in an airport concourse with a suitcase" loading="lazy" width="1536" height="1024" /><span>YOUR CAREER. YOUR EMPLOYER. YOUR NEXT CHAPTER.</span></div>}<div><span className="kicker">INTERNATIONAL DIRECT-HIRE CAREER PATH</span><h2>A new destination.<br /><em>A long-term place to belong.</em></h2><p>Build your next chapter with a healthcare employer. In a direct-hire placement, the healthcare facility hires you directly for a permanent role, with employment terms agreed between you and the employer.</p><p>Tell Rapid Nova about your background and your interest in international direct hire. Our team can review your enquiry and discuss potential opportunities, eligibility, and the arrangements for a specific vacancy.</p><ul className="rn-direct-hire-points"><li>Explore permanent employment with the hiring facility.</li><li>Discuss the team, location, clinical setting, and career development.</li><li>Review the employer’s pay, benefits, and any relocation or sponsorship arrangements.</li></ul><a href={compact ? '/international-nursing/direct-hire' : '/apply?path=international-direct-hire'} className="btn btn-capri">{compact ? 'Explore the direct-hire path' : 'Enquire about international direct hire'} →</a><p className="rn-direct-hire-note">Opportunities, sponsorship, and support depend on the employer, vacancy, and your eligibility.</p></div></div>
    {!compact && <><div className="rn-direct-hire-journey"><span className="kicker">FROM FIRST ENQUIRY TO YOUR NEXT CHAPTER</span><h2>Your direct-hire <em>journey.</em></h2><div className="rn-preparation-grid">{[
      ['01', 'Share your experience', 'Submit your resume, current location, qualifications, registration details, and preferred destination.'],
      ['02', 'Explore employer opportunities', 'Discuss suitable vacancies and employer interviews when opportunities are available.'],
      ['03', 'Review the offer and requirements', 'Clarify employment terms, required registration and documents, and any employer sponsorship or relocation support.'],
      ['04', 'Prepare for your start', 'Confirm the necessary approvals, onboarding plan, and agreed arrangements before travelling or starting work.'],
    ].map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div><div className="rn-direct-hire-comparison"><h2>Understand your <em>placement options.</em></h2><div className="rn-offer-grid"><article><span className="kicker">DIRECT HIRE</span><h3>Employment directly with the facility</h3><p>You join the hiring healthcare organisation as its employee. Confirm the permanent role, employer benefits, and offer terms before accepting.</p></article><article><span className="kicker">TEMPORARY-TO-PERMANENT</span><h3>A temporary placement with a possible transition</h3><p>You start with an agreed temporary arrangement. A later permanent hire depends on the facility, your preferences, and the placement terms.</p></article></div></div><div className="rn-direct-hire-faq"><h2>Before you <em>take the next step.</em></h2>{[
      ['Who employs me in a direct-hire role?', 'The hiring healthcare facility is your employer. Your offer should explain your role, working conditions, pay, benefits, and other employment terms.'],
      ['Is sponsorship or relocation included?', 'Confirm this for the individual vacancy. Support and eligibility vary by employer and destination. Ask who handles each stage, what costs apply, and what arrangements may be available for dependants.'],
      ['How long does the process take?', 'Timelines vary with employer recruitment, professional registration, documentation, and any work authorisation requirements. Ask about the expected stages for your opportunity; no fixed start date is guaranteed.'],
      ['What do I need for my first enquiry?', 'Start with an up-to-date PDF resume under 3 MB, your qualifications, current registration, clinical experience, current location, and preferred destination. You can include these details in the application message.'],
    ].map(([question, answer]) => <details className="faq-item" key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></>}
  </div></section>;
}
